// <auto-generated />
using System;
using BM.Social.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BM.WebAPI.Migrations.SocialDb
{
    [DbContext(typeof(SocialDbContext))]
    [Migration("20250328182759_SocialV1")]
    partial class SocialV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BM.Social.Domain.SocialBlog", b =>
                {
                    b.Property<int>("blogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("blogID"));

                    b.Property<string>("blogContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("blogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("blogLike")
                        .HasColumnType("int");

                    b.Property<string>("blogStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blogTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("blogID");

                    b.ToTable("SocialBlog", "social");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialBlogComment", b =>
                {
                    b.Property<int>("commentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentID"));

                    b.Property<int>("blogID")
                        .HasColumnType("int");

                    b.Property<string>("commentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("commentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("commentLike")
                        .HasColumnType("int");

                    b.Property<string>("commentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("commentID");

                    b.HasIndex("blogID");

                    b.ToTable("socialBlogComments");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialGroup", b =>
                {
                    b.Property<int>("groupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("groupID"));

                    b.Property<DateTime>("groupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("groupDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("groupStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("srcID")
                        .HasColumnType("int");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("groupID");

                    b.ToTable("socialGroups");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialGroupUser", b =>
                {
                    b.Property<int>("socialGroupUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("socialGroupUserID"));

                    b.Property<int>("groupID")
                        .HasColumnType("int");

                    b.Property<DateTime>("memberDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("socialGroupUserID");

                    b.HasIndex("groupID");

                    b.ToTable("socialGroupUsers");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialMessage", b =>
                {
                    b.Property<int>("messageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("messageID"));

                    b.Property<int>("SocialGroupgroupID")
                        .HasColumnType("int");

                    b.Property<int>("groupID")
                        .HasColumnType("int");

                    b.Property<string>("messageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("messageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("messageStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receiverID")
                        .HasColumnType("int");

                    b.Property<int>("senderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("messageID");

                    b.HasIndex("SocialGroupgroupID");

                    b.ToTable("socialMessages");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialSrc", b =>
                {
                    b.Property<int>("srcID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("srcID"));

                    b.Property<string>("imageSrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("srcDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("srcName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("srcTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("srcID");

                    b.ToTable("SocialSrc", "social");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialSrcBlog", b =>
                {
                    b.Property<int>("srcBlogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("srcBlogID"));

                    b.Property<int>("blogID")
                        .HasColumnType("int");

                    b.Property<int>("position")
                        .HasColumnType("int");

                    b.Property<DateTime>("srcBlogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("srcID")
                        .HasColumnType("int");

                    b.HasKey("srcBlogID");

                    b.HasIndex("blogID");

                    b.HasIndex("srcID");

                    b.ToTable("socialSrcBlogs");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialSrcMessage", b =>
                {
                    b.Property<int>("srcMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("srcMessageID"));

                    b.Property<int>("messageID")
                        .HasColumnType("int");

                    b.Property<int>("srcID")
                        .HasColumnType("int");

                    b.Property<DateTime>("srcMessageDate")
                        .HasColumnType("datetime2");

                    b.HasKey("srcMessageID");

                    b.HasIndex("messageID");

                    b.HasIndex("srcID");

                    b.ToTable("socialSrcMessages");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialBlogComment", b =>
                {
                    b.HasOne("BM.Social.Domain.SocialBlog", "SocialBlog")
                        .WithMany("SocialBlogComments")
                        .HasForeignKey("blogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialBlog");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialGroupUser", b =>
                {
                    b.HasOne("BM.Social.Domain.SocialGroup", "SocialGroup")
                        .WithMany("SocialGroupUsers")
                        .HasForeignKey("groupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialGroup");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialMessage", b =>
                {
                    b.HasOne("BM.Social.Domain.SocialGroup", "SocialGroup")
                        .WithMany("SocialMessages")
                        .HasForeignKey("SocialGroupgroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialGroup");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialSrcBlog", b =>
                {
                    b.HasOne("BM.Social.Domain.SocialBlog", "SocialBlog")
                        .WithMany("SocialSrcBlogs")
                        .HasForeignKey("blogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BM.Social.Domain.SocialSrc", "SocialSrc")
                        .WithMany("SocialSrcBlogs")
                        .HasForeignKey("srcID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialBlog");

                    b.Navigation("SocialSrc");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialSrcMessage", b =>
                {
                    b.HasOne("BM.Social.Domain.SocialMessage", "SocialMessage")
                        .WithMany("SocialSrcMessages")
                        .HasForeignKey("messageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BM.Social.Domain.SocialSrc", "SocialSrc")
                        .WithMany("SocialSrcMessages")
                        .HasForeignKey("srcID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialMessage");

                    b.Navigation("SocialSrc");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialBlog", b =>
                {
                    b.Navigation("SocialBlogComments");

                    b.Navigation("SocialSrcBlogs");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialGroup", b =>
                {
                    b.Navigation("SocialGroupUsers");

                    b.Navigation("SocialMessages");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialMessage", b =>
                {
                    b.Navigation("SocialSrcMessages");
                });

            modelBuilder.Entity("BM.Social.Domain.SocialSrc", b =>
                {
                    b.Navigation("SocialSrcBlogs");

                    b.Navigation("SocialSrcMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
